eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 9999
spring:
  application:
    name: zuul-server
zuul:
  routes:
    api-a:
      path: /api-member/**
      service-id: member-service
    api-b:
      path: /api-order/**
      service-id: order-service